<?php
/**
 * ApplicationDescription
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * ApplicationDescription Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/7.2.4/#7.2.4.6.5).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApplicationDescription implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApplicationDescription';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'application_uri' => 'string',
        'product_uri' => 'string',
        'application_name' => '\TechDock\OpcUaWebApiClient\Model\LocalizedText',
        'application_type' => 'int',
        'gateway_server_uri' => 'string',
        'discovery_profile_uri' => 'string',
        'discovery_urls' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'application_uri' => null,
        'product_uri' => null,
        'application_name' => null,
        'application_type' => 'ApplicationType',
        'gateway_server_uri' => null,
        'discovery_profile_uri' => null,
        'discovery_urls' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'application_uri' => false,
        'product_uri' => false,
        'application_name' => false,
        'application_type' => false,
        'gateway_server_uri' => false,
        'discovery_profile_uri' => false,
        'discovery_urls' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'application_uri' => 'ApplicationUri',
        'product_uri' => 'ProductUri',
        'application_name' => 'ApplicationName',
        'application_type' => 'ApplicationType',
        'gateway_server_uri' => 'GatewayServerUri',
        'discovery_profile_uri' => 'DiscoveryProfileUri',
        'discovery_urls' => 'DiscoveryUrls'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'application_uri' => 'setApplicationUri',
        'product_uri' => 'setProductUri',
        'application_name' => 'setApplicationName',
        'application_type' => 'setApplicationType',
        'gateway_server_uri' => 'setGatewayServerUri',
        'discovery_profile_uri' => 'setDiscoveryProfileUri',
        'discovery_urls' => 'setDiscoveryUrls'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'application_uri' => 'getApplicationUri',
        'product_uri' => 'getProductUri',
        'application_name' => 'getApplicationName',
        'application_type' => 'getApplicationType',
        'gateway_server_uri' => 'getGatewayServerUri',
        'discovery_profile_uri' => 'getDiscoveryProfileUri',
        'discovery_urls' => 'getDiscoveryUrls'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('application_uri', $data ?? [], null);
        $this->setIfExists('product_uri', $data ?? [], null);
        $this->setIfExists('application_name', $data ?? [], null);
        $this->setIfExists('application_type', $data ?? [], null);
        $this->setIfExists('gateway_server_uri', $data ?? [], null);
        $this->setIfExists('discovery_profile_uri', $data ?? [], null);
        $this->setIfExists('discovery_urls', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application_uri
     *
     * @return string|null
     */
    public function getApplicationUri()
    {
        return $this->container['application_uri'];
    }

    /**
     * Sets application_uri
     *
     * @param string|null $application_uri application_uri
     *
     * @return self
     */
    public function setApplicationUri($application_uri)
    {
        if (is_null($application_uri)) {
            throw new \InvalidArgumentException('non-nullable application_uri cannot be null');
        }
        $this->container['application_uri'] = $application_uri;

        return $this;
    }

    /**
     * Gets product_uri
     *
     * @return string|null
     */
    public function getProductUri()
    {
        return $this->container['product_uri'];
    }

    /**
     * Sets product_uri
     *
     * @param string|null $product_uri product_uri
     *
     * @return self
     */
    public function setProductUri($product_uri)
    {
        if (is_null($product_uri)) {
            throw new \InvalidArgumentException('non-nullable product_uri cannot be null');
        }
        $this->container['product_uri'] = $product_uri;

        return $this;
    }

    /**
     * Gets application_name
     *
     * @return \TechDock\OpcUaWebApiClient\Model\LocalizedText|null
     */
    public function getApplicationName()
    {
        return $this->container['application_name'];
    }

    /**
     * Sets application_name
     *
     * @param \TechDock\OpcUaWebApiClient\Model\LocalizedText|null $application_name application_name
     *
     * @return self
     */
    public function setApplicationName($application_name)
    {
        if (is_null($application_name)) {
            throw new \InvalidArgumentException('non-nullable application_name cannot be null');
        }
        $this->container['application_name'] = $application_name;

        return $this;
    }

    /**
     * Gets application_type
     *
     * @return int|null
     */
    public function getApplicationType()
    {
        return $this->container['application_type'];
    }

    /**
     * Sets application_type
     *
     * @param int|null $application_type [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.4).
     *
     * @return self
     */
    public function setApplicationType($application_type)
    {
        if (is_null($application_type)) {
            throw new \InvalidArgumentException('non-nullable application_type cannot be null');
        }
        $this->container['application_type'] = $application_type;

        return $this;
    }

    /**
     * Gets gateway_server_uri
     *
     * @return string|null
     */
    public function getGatewayServerUri()
    {
        return $this->container['gateway_server_uri'];
    }

    /**
     * Sets gateway_server_uri
     *
     * @param string|null $gateway_server_uri gateway_server_uri
     *
     * @return self
     */
    public function setGatewayServerUri($gateway_server_uri)
    {
        if (is_null($gateway_server_uri)) {
            throw new \InvalidArgumentException('non-nullable gateway_server_uri cannot be null');
        }
        $this->container['gateway_server_uri'] = $gateway_server_uri;

        return $this;
    }

    /**
     * Gets discovery_profile_uri
     *
     * @return string|null
     */
    public function getDiscoveryProfileUri()
    {
        return $this->container['discovery_profile_uri'];
    }

    /**
     * Sets discovery_profile_uri
     *
     * @param string|null $discovery_profile_uri discovery_profile_uri
     *
     * @return self
     */
    public function setDiscoveryProfileUri($discovery_profile_uri)
    {
        if (is_null($discovery_profile_uri)) {
            throw new \InvalidArgumentException('non-nullable discovery_profile_uri cannot be null');
        }
        $this->container['discovery_profile_uri'] = $discovery_profile_uri;

        return $this;
    }

    /**
     * Gets discovery_urls
     *
     * @return string[]|null
     */
    public function getDiscoveryUrls()
    {
        return $this->container['discovery_urls'];
    }

    /**
     * Sets discovery_urls
     *
     * @param string[]|null $discovery_urls discovery_urls
     *
     * @return self
     */
    public function setDiscoveryUrls($discovery_urls)
    {
        if (is_null($discovery_urls)) {
            throw new \InvalidArgumentException('non-nullable discovery_urls cannot be null');
        }
        $this->container['discovery_urls'] = $discovery_urls;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


