<?php
/**
 * BrokerDataSetWriterTransportDataType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * BrokerDataSetWriterTransportDataType Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.4.2/#6.4.2.5.7).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BrokerDataSetWriterTransportDataType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BrokerDataSetWriterTransportDataType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'queue_name' => 'string',
        'resource_uri' => 'string',
        'authentication_profile_uri' => 'string',
        'requested_delivery_guarantee' => 'int',
        'meta_data_queue_name' => 'string',
        'meta_data_update_time' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'queue_name' => null,
        'resource_uri' => null,
        'authentication_profile_uri' => null,
        'requested_delivery_guarantee' => 'BrokerTransportQualityOfService',
        'meta_data_queue_name' => null,
        'meta_data_update_time' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'queue_name' => false,
        'resource_uri' => false,
        'authentication_profile_uri' => false,
        'requested_delivery_guarantee' => false,
        'meta_data_queue_name' => false,
        'meta_data_update_time' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'queue_name' => 'QueueName',
        'resource_uri' => 'ResourceUri',
        'authentication_profile_uri' => 'AuthenticationProfileUri',
        'requested_delivery_guarantee' => 'RequestedDeliveryGuarantee',
        'meta_data_queue_name' => 'MetaDataQueueName',
        'meta_data_update_time' => 'MetaDataUpdateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'queue_name' => 'setQueueName',
        'resource_uri' => 'setResourceUri',
        'authentication_profile_uri' => 'setAuthenticationProfileUri',
        'requested_delivery_guarantee' => 'setRequestedDeliveryGuarantee',
        'meta_data_queue_name' => 'setMetaDataQueueName',
        'meta_data_update_time' => 'setMetaDataUpdateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'queue_name' => 'getQueueName',
        'resource_uri' => 'getResourceUri',
        'authentication_profile_uri' => 'getAuthenticationProfileUri',
        'requested_delivery_guarantee' => 'getRequestedDeliveryGuarantee',
        'meta_data_queue_name' => 'getMetaDataQueueName',
        'meta_data_update_time' => 'getMetaDataUpdateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('queue_name', $data ?? [], null);
        $this->setIfExists('resource_uri', $data ?? [], null);
        $this->setIfExists('authentication_profile_uri', $data ?? [], null);
        $this->setIfExists('requested_delivery_guarantee', $data ?? [], null);
        $this->setIfExists('meta_data_queue_name', $data ?? [], null);
        $this->setIfExists('meta_data_update_time', $data ?? [], 0);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets queue_name
     *
     * @return string|null
     */
    public function getQueueName()
    {
        return $this->container['queue_name'];
    }

    /**
     * Sets queue_name
     *
     * @param string|null $queue_name queue_name
     *
     * @return self
     */
    public function setQueueName($queue_name)
    {
        if (is_null($queue_name)) {
            throw new \InvalidArgumentException('non-nullable queue_name cannot be null');
        }
        $this->container['queue_name'] = $queue_name;

        return $this;
    }

    /**
     * Gets resource_uri
     *
     * @return string|null
     */
    public function getResourceUri()
    {
        return $this->container['resource_uri'];
    }

    /**
     * Sets resource_uri
     *
     * @param string|null $resource_uri resource_uri
     *
     * @return self
     */
    public function setResourceUri($resource_uri)
    {
        if (is_null($resource_uri)) {
            throw new \InvalidArgumentException('non-nullable resource_uri cannot be null');
        }
        $this->container['resource_uri'] = $resource_uri;

        return $this;
    }

    /**
     * Gets authentication_profile_uri
     *
     * @return string|null
     */
    public function getAuthenticationProfileUri()
    {
        return $this->container['authentication_profile_uri'];
    }

    /**
     * Sets authentication_profile_uri
     *
     * @param string|null $authentication_profile_uri authentication_profile_uri
     *
     * @return self
     */
    public function setAuthenticationProfileUri($authentication_profile_uri)
    {
        if (is_null($authentication_profile_uri)) {
            throw new \InvalidArgumentException('non-nullable authentication_profile_uri cannot be null');
        }
        $this->container['authentication_profile_uri'] = $authentication_profile_uri;

        return $this;
    }

    /**
     * Gets requested_delivery_guarantee
     *
     * @return int|null
     */
    public function getRequestedDeliveryGuarantee()
    {
        return $this->container['requested_delivery_guarantee'];
    }

    /**
     * Sets requested_delivery_guarantee
     *
     * @param int|null $requested_delivery_guarantee [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.4.2/#6.4.2.1).
     *
     * @return self
     */
    public function setRequestedDeliveryGuarantee($requested_delivery_guarantee)
    {
        if (is_null($requested_delivery_guarantee)) {
            throw new \InvalidArgumentException('non-nullable requested_delivery_guarantee cannot be null');
        }
        $this->container['requested_delivery_guarantee'] = $requested_delivery_guarantee;

        return $this;
    }

    /**
     * Gets meta_data_queue_name
     *
     * @return string|null
     */
    public function getMetaDataQueueName()
    {
        return $this->container['meta_data_queue_name'];
    }

    /**
     * Sets meta_data_queue_name
     *
     * @param string|null $meta_data_queue_name meta_data_queue_name
     *
     * @return self
     */
    public function setMetaDataQueueName($meta_data_queue_name)
    {
        if (is_null($meta_data_queue_name)) {
            throw new \InvalidArgumentException('non-nullable meta_data_queue_name cannot be null');
        }
        $this->container['meta_data_queue_name'] = $meta_data_queue_name;

        return $this;
    }

    /**
     * Gets meta_data_update_time
     *
     * @return float|null
     */
    public function getMetaDataUpdateTime()
    {
        return $this->container['meta_data_update_time'];
    }

    /**
     * Sets meta_data_update_time
     *
     * @param float|null $meta_data_update_time meta_data_update_time
     *
     * @return self
     */
    public function setMetaDataUpdateTime($meta_data_update_time)
    {
        if (is_null($meta_data_update_time)) {
            throw new \InvalidArgumentException('non-nullable meta_data_update_time cannot be null');
        }
        $this->container['meta_data_update_time'] = $meta_data_update_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


