<?php
/**
 * DataSetWriterDataType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * DataSetWriterDataType Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.4/#6.2.4.5.1).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DataSetWriterDataType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DataSetWriterDataType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'enabled' => 'bool',
        'data_set_writer_id' => 'int',
        'data_set_field_content_mask' => 'int',
        'key_frame_count' => 'int',
        'data_set_name' => 'string',
        'data_set_writer_properties' => '\TechDock\OpcUaWebApiClient\Model\KeyValuePair[]',
        'transport_settings' => 'object',
        'message_settings' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'enabled' => null,
        'data_set_writer_id' => 'int32',
        'data_set_field_content_mask' => 'int64',
        'key_frame_count' => 'int64',
        'data_set_name' => null,
        'data_set_writer_properties' => null,
        'transport_settings' => null,
        'message_settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'enabled' => false,
        'data_set_writer_id' => false,
        'data_set_field_content_mask' => false,
        'key_frame_count' => false,
        'data_set_name' => false,
        'data_set_writer_properties' => false,
        'transport_settings' => false,
        'message_settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'enabled' => 'Enabled',
        'data_set_writer_id' => 'DataSetWriterId',
        'data_set_field_content_mask' => 'DataSetFieldContentMask',
        'key_frame_count' => 'KeyFrameCount',
        'data_set_name' => 'DataSetName',
        'data_set_writer_properties' => 'DataSetWriterProperties',
        'transport_settings' => 'TransportSettings',
        'message_settings' => 'MessageSettings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'enabled' => 'setEnabled',
        'data_set_writer_id' => 'setDataSetWriterId',
        'data_set_field_content_mask' => 'setDataSetFieldContentMask',
        'key_frame_count' => 'setKeyFrameCount',
        'data_set_name' => 'setDataSetName',
        'data_set_writer_properties' => 'setDataSetWriterProperties',
        'transport_settings' => 'setTransportSettings',
        'message_settings' => 'setMessageSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'enabled' => 'getEnabled',
        'data_set_writer_id' => 'getDataSetWriterId',
        'data_set_field_content_mask' => 'getDataSetFieldContentMask',
        'key_frame_count' => 'getKeyFrameCount',
        'data_set_name' => 'getDataSetName',
        'data_set_writer_properties' => 'getDataSetWriterProperties',
        'transport_settings' => 'getTransportSettings',
        'message_settings' => 'getMessageSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], false);
        $this->setIfExists('data_set_writer_id', $data ?? [], 0);
        $this->setIfExists('data_set_field_content_mask', $data ?? [], 0);
        $this->setIfExists('key_frame_count', $data ?? [], 0);
        $this->setIfExists('data_set_name', $data ?? [], null);
        $this->setIfExists('data_set_writer_properties', $data ?? [], null);
        $this->setIfExists('transport_settings', $data ?? [], null);
        $this->setIfExists('message_settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['data_set_writer_id']) && ($this->container['data_set_writer_id'] > 65535)) {
            $invalidProperties[] = "invalid value for 'data_set_writer_id', must be smaller than or equal to 65535.";
        }

        if (!is_null($this->container['data_set_writer_id']) && ($this->container['data_set_writer_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'data_set_writer_id', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['data_set_field_content_mask']) && ($this->container['data_set_field_content_mask'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'data_set_field_content_mask', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['data_set_field_content_mask']) && ($this->container['data_set_field_content_mask'] < 0)) {
            $invalidProperties[] = "invalid value for 'data_set_field_content_mask', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['key_frame_count']) && ($this->container['key_frame_count'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'key_frame_count', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['key_frame_count']) && ($this->container['key_frame_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'key_frame_count', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets data_set_writer_id
     *
     * @return int|null
     */
    public function getDataSetWriterId()
    {
        return $this->container['data_set_writer_id'];
    }

    /**
     * Sets data_set_writer_id
     *
     * @param int|null $data_set_writer_id data_set_writer_id
     *
     * @return self
     */
    public function setDataSetWriterId($data_set_writer_id)
    {
        if (is_null($data_set_writer_id)) {
            throw new \InvalidArgumentException('non-nullable data_set_writer_id cannot be null');
        }

        if (($data_set_writer_id > 65535)) {
            throw new \InvalidArgumentException('invalid value for $data_set_writer_id when calling DataSetWriterDataType., must be smaller than or equal to 65535.');
        }
        if (($data_set_writer_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $data_set_writer_id when calling DataSetWriterDataType., must be bigger than or equal to 0.');
        }

        $this->container['data_set_writer_id'] = $data_set_writer_id;

        return $this;
    }

    /**
     * Gets data_set_field_content_mask
     *
     * @return int|null
     */
    public function getDataSetFieldContentMask()
    {
        return $this->container['data_set_field_content_mask'];
    }

    /**
     * Sets data_set_field_content_mask
     *
     * @param int|null $data_set_field_content_mask data_set_field_content_mask
     *
     * @return self
     */
    public function setDataSetFieldContentMask($data_set_field_content_mask)
    {
        if (is_null($data_set_field_content_mask)) {
            throw new \InvalidArgumentException('non-nullable data_set_field_content_mask cannot be null');
        }

        if (($data_set_field_content_mask > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $data_set_field_content_mask when calling DataSetWriterDataType., must be smaller than or equal to 4294967295.');
        }
        if (($data_set_field_content_mask < 0)) {
            throw new \InvalidArgumentException('invalid value for $data_set_field_content_mask when calling DataSetWriterDataType., must be bigger than or equal to 0.');
        }

        $this->container['data_set_field_content_mask'] = $data_set_field_content_mask;

        return $this;
    }

    /**
     * Gets key_frame_count
     *
     * @return int|null
     */
    public function getKeyFrameCount()
    {
        return $this->container['key_frame_count'];
    }

    /**
     * Sets key_frame_count
     *
     * @param int|null $key_frame_count key_frame_count
     *
     * @return self
     */
    public function setKeyFrameCount($key_frame_count)
    {
        if (is_null($key_frame_count)) {
            throw new \InvalidArgumentException('non-nullable key_frame_count cannot be null');
        }

        if (($key_frame_count > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $key_frame_count when calling DataSetWriterDataType., must be smaller than or equal to 4294967295.');
        }
        if (($key_frame_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $key_frame_count when calling DataSetWriterDataType., must be bigger than or equal to 0.');
        }

        $this->container['key_frame_count'] = $key_frame_count;

        return $this;
    }

    /**
     * Gets data_set_name
     *
     * @return string|null
     */
    public function getDataSetName()
    {
        return $this->container['data_set_name'];
    }

    /**
     * Sets data_set_name
     *
     * @param string|null $data_set_name data_set_name
     *
     * @return self
     */
    public function setDataSetName($data_set_name)
    {
        if (is_null($data_set_name)) {
            throw new \InvalidArgumentException('non-nullable data_set_name cannot be null');
        }
        $this->container['data_set_name'] = $data_set_name;

        return $this;
    }

    /**
     * Gets data_set_writer_properties
     *
     * @return \TechDock\OpcUaWebApiClient\Model\KeyValuePair[]|null
     */
    public function getDataSetWriterProperties()
    {
        return $this->container['data_set_writer_properties'];
    }

    /**
     * Sets data_set_writer_properties
     *
     * @param \TechDock\OpcUaWebApiClient\Model\KeyValuePair[]|null $data_set_writer_properties data_set_writer_properties
     *
     * @return self
     */
    public function setDataSetWriterProperties($data_set_writer_properties)
    {
        if (is_null($data_set_writer_properties)) {
            throw new \InvalidArgumentException('non-nullable data_set_writer_properties cannot be null');
        }
        $this->container['data_set_writer_properties'] = $data_set_writer_properties;

        return $this;
    }

    /**
     * Gets transport_settings
     *
     * @return object|null
     */
    public function getTransportSettings()
    {
        return $this->container['transport_settings'];
    }

    /**
     * Sets transport_settings
     *
     * @param object|null $transport_settings transport_settings
     *
     * @return self
     */
    public function setTransportSettings($transport_settings)
    {
        if (is_null($transport_settings)) {
            throw new \InvalidArgumentException('non-nullable transport_settings cannot be null');
        }
        $this->container['transport_settings'] = $transport_settings;

        return $this;
    }

    /**
     * Gets message_settings
     *
     * @return object|null
     */
    public function getMessageSettings()
    {
        return $this->container['message_settings'];
    }

    /**
     * Sets message_settings
     *
     * @param object|null $message_settings message_settings
     *
     * @return self
     */
    public function setMessageSettings($message_settings)
    {
        if (is_null($message_settings)) {
            throw new \InvalidArgumentException('non-nullable message_settings cannot be null');
        }
        $this->container['message_settings'] = $message_settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


