<?php
/**
 * DiagnosticInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * DiagnosticInfo Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/Core/Part4/v105/docs/7.12).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DiagnosticInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DiagnosticInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'symbolic_id' => 'int',
        'namespace_uri' => 'int',
        'locale' => 'int',
        'localized_text' => 'int',
        'additional_info' => 'string',
        'inner_status_code' => '\TechDock\OpcUaWebApiClient\Model\StatusCode',
        'inner_diagnostic_info' => '\TechDock\OpcUaWebApiClient\Model\DiagnosticInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'symbolic_id' => 'int32',
        'namespace_uri' => 'int32',
        'locale' => 'int32',
        'localized_text' => 'int32',
        'additional_info' => null,
        'inner_status_code' => null,
        'inner_diagnostic_info' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'symbolic_id' => false,
        'namespace_uri' => false,
        'locale' => false,
        'localized_text' => false,
        'additional_info' => false,
        'inner_status_code' => false,
        'inner_diagnostic_info' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'symbolic_id' => 'SymbolicId',
        'namespace_uri' => 'NamespaceUri',
        'locale' => 'Locale',
        'localized_text' => 'LocalizedText',
        'additional_info' => 'AdditionalInfo',
        'inner_status_code' => 'InnerStatusCode',
        'inner_diagnostic_info' => 'InnerDiagnosticInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'symbolic_id' => 'setSymbolicId',
        'namespace_uri' => 'setNamespaceUri',
        'locale' => 'setLocale',
        'localized_text' => 'setLocalizedText',
        'additional_info' => 'setAdditionalInfo',
        'inner_status_code' => 'setInnerStatusCode',
        'inner_diagnostic_info' => 'setInnerDiagnosticInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'symbolic_id' => 'getSymbolicId',
        'namespace_uri' => 'getNamespaceUri',
        'locale' => 'getLocale',
        'localized_text' => 'getLocalizedText',
        'additional_info' => 'getAdditionalInfo',
        'inner_status_code' => 'getInnerStatusCode',
        'inner_diagnostic_info' => 'getInnerDiagnosticInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('symbolic_id', $data ?? [], null);
        $this->setIfExists('namespace_uri', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('localized_text', $data ?? [], null);
        $this->setIfExists('additional_info', $data ?? [], null);
        $this->setIfExists('inner_status_code', $data ?? [], null);
        $this->setIfExists('inner_diagnostic_info', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets symbolic_id
     *
     * @return int|null
     */
    public function getSymbolicId()
    {
        return $this->container['symbolic_id'];
    }

    /**
     * Sets symbolic_id
     *
     * @param int|null $symbolic_id symbolic_id
     *
     * @return self
     */
    public function setSymbolicId($symbolic_id)
    {
        if (is_null($symbolic_id)) {
            throw new \InvalidArgumentException('non-nullable symbolic_id cannot be null');
        }
        $this->container['symbolic_id'] = $symbolic_id;

        return $this;
    }

    /**
     * Gets namespace_uri
     *
     * @return int|null
     */
    public function getNamespaceUri()
    {
        return $this->container['namespace_uri'];
    }

    /**
     * Sets namespace_uri
     *
     * @param int|null $namespace_uri namespace_uri
     *
     * @return self
     */
    public function setNamespaceUri($namespace_uri)
    {
        if (is_null($namespace_uri)) {
            throw new \InvalidArgumentException('non-nullable namespace_uri cannot be null');
        }
        $this->container['namespace_uri'] = $namespace_uri;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return int|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param int|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets localized_text
     *
     * @return int|null
     */
    public function getLocalizedText()
    {
        return $this->container['localized_text'];
    }

    /**
     * Sets localized_text
     *
     * @param int|null $localized_text localized_text
     *
     * @return self
     */
    public function setLocalizedText($localized_text)
    {
        if (is_null($localized_text)) {
            throw new \InvalidArgumentException('non-nullable localized_text cannot be null');
        }
        $this->container['localized_text'] = $localized_text;

        return $this;
    }

    /**
     * Gets additional_info
     *
     * @return string|null
     */
    public function getAdditionalInfo()
    {
        return $this->container['additional_info'];
    }

    /**
     * Sets additional_info
     *
     * @param string|null $additional_info additional_info
     *
     * @return self
     */
    public function setAdditionalInfo($additional_info)
    {
        if (is_null($additional_info)) {
            throw new \InvalidArgumentException('non-nullable additional_info cannot be null');
        }
        $this->container['additional_info'] = $additional_info;

        return $this;
    }

    /**
     * Gets inner_status_code
     *
     * @return \TechDock\OpcUaWebApiClient\Model\StatusCode|null
     */
    public function getInnerStatusCode()
    {
        return $this->container['inner_status_code'];
    }

    /**
     * Sets inner_status_code
     *
     * @param \TechDock\OpcUaWebApiClient\Model\StatusCode|null $inner_status_code inner_status_code
     *
     * @return self
     */
    public function setInnerStatusCode($inner_status_code)
    {
        if (is_null($inner_status_code)) {
            throw new \InvalidArgumentException('non-nullable inner_status_code cannot be null');
        }
        $this->container['inner_status_code'] = $inner_status_code;

        return $this;
    }

    /**
     * Gets inner_diagnostic_info
     *
     * @return \TechDock\OpcUaWebApiClient\Model\DiagnosticInfo|null
     */
    public function getInnerDiagnosticInfo()
    {
        return $this->container['inner_diagnostic_info'];
    }

    /**
     * Sets inner_diagnostic_info
     *
     * @param \TechDock\OpcUaWebApiClient\Model\DiagnosticInfo|null $inner_diagnostic_info inner_diagnostic_info
     *
     * @return self
     */
    public function setInnerDiagnosticInfo($inner_diagnostic_info)
    {
        if (is_null($inner_diagnostic_info)) {
            throw new \InvalidArgumentException('non-nullable inner_diagnostic_info cannot be null');
        }
        $this->container['inner_diagnostic_info'] = $inner_diagnostic_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


