<?php
/**
 * JsonDataSetMessageContentMaskBits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * JsonDataSetMessageContentMaskBits Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.3.2/#6.3.2.3.1).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JsonDataSetMessageContentMaskBits
{
    /**
     * Possible values of this enum
     */
    public const DATA_SET_WRITER_ID = 1;

    public const META_DATA_VERSION = 2;

    public const SEQUENCE_NUMBER = 4;

    public const TIMESTAMP = 8;

    public const STATUS = 16;

    public const MESSAGE_TYPE = 32;

    public const DATA_SET_WRITER_NAME = 64;

    public const FIELD_ENCODING1 = 128;

    public const PUBLISHER_ID = 256;

    public const WRITER_GROUP_NAME = 512;

    public const MINOR_VERSION = 1024;

    public const FIELD_ENCODING2 = 2048;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DATA_SET_WRITER_ID,
            self::META_DATA_VERSION,
            self::SEQUENCE_NUMBER,
            self::TIMESTAMP,
            self::STATUS,
            self::MESSAGE_TYPE,
            self::DATA_SET_WRITER_NAME,
            self::FIELD_ENCODING1,
            self::PUBLISHER_ID,
            self::WRITER_GROUP_NAME,
            self::MINOR_VERSION,
            self::FIELD_ENCODING2
        ];
    }
}


