<?php
/**
 * JsonNetworkMessageContentMaskBits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * JsonNetworkMessageContentMaskBits Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.3.2/#6.3.2.1.1).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JsonNetworkMessageContentMaskBits
{
    /**
     * Possible values of this enum
     */
    public const NETWORK_MESSAGE_HEADER = 1;

    public const DATA_SET_MESSAGE_HEADER = 2;

    public const SINGLE_DATA_SET_MESSAGE = 4;

    public const PUBLISHER_ID = 8;

    public const DATA_SET_CLASS_ID = 16;

    public const REPLY_TO = 32;

    public const WRITER_GROUP_NAME = 64;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NETWORK_MESSAGE_HEADER,
            self::DATA_SET_MESSAGE_HEADER,
            self::SINGLE_DATA_SET_MESSAGE,
            self::PUBLISHER_ID,
            self::DATA_SET_CLASS_ID,
            self::REPLY_TO,
            self::WRITER_GROUP_NAME
        ];
    }
}


