<?php
/**
 * JsonDataSetMessage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * JsonDataSetMessage Class Doc Comment
 *
 * @category Class
 * @description [Link to specification]().
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JsonDataSetMessage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JsonDataSetMessage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'data_set_writer_id' => 'int',
        'data_set_writer_name' => 'string',
        'publisher_id' => 'string',
        'writer_group_name' => 'string',
        'sequence_number' => 'int',
        'meta_data_version' => '\TechDock\OpcUaWebApiClient\Model\ConfigurationVersionDataType',
        'minor_version' => 'int',
        'timestamp' => '\DateTime',
        'status' => '\TechDock\OpcUaWebApiClient\Model\StatusCode',
        'message_type' => 'string',
        'payload' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'data_set_writer_id' => 'int32',
        'data_set_writer_name' => null,
        'publisher_id' => null,
        'writer_group_name' => null,
        'sequence_number' => 'int64',
        'meta_data_version' => null,
        'minor_version' => 'int64',
        'timestamp' => 'date-time',
        'status' => null,
        'message_type' => null,
        'payload' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'data_set_writer_id' => false,
        'data_set_writer_name' => false,
        'publisher_id' => false,
        'writer_group_name' => false,
        'sequence_number' => false,
        'meta_data_version' => false,
        'minor_version' => false,
        'timestamp' => false,
        'status' => false,
        'message_type' => false,
        'payload' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'data_set_writer_id' => 'DataSetWriterId',
        'data_set_writer_name' => 'DataSetWriterName',
        'publisher_id' => 'PublisherId',
        'writer_group_name' => 'WriterGroupName',
        'sequence_number' => 'SequenceNumber',
        'meta_data_version' => 'MetaDataVersion',
        'minor_version' => 'MinorVersion',
        'timestamp' => 'Timestamp',
        'status' => 'Status',
        'message_type' => 'MessageType',
        'payload' => 'Payload'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'data_set_writer_id' => 'setDataSetWriterId',
        'data_set_writer_name' => 'setDataSetWriterName',
        'publisher_id' => 'setPublisherId',
        'writer_group_name' => 'setWriterGroupName',
        'sequence_number' => 'setSequenceNumber',
        'meta_data_version' => 'setMetaDataVersion',
        'minor_version' => 'setMinorVersion',
        'timestamp' => 'setTimestamp',
        'status' => 'setStatus',
        'message_type' => 'setMessageType',
        'payload' => 'setPayload'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'data_set_writer_id' => 'getDataSetWriterId',
        'data_set_writer_name' => 'getDataSetWriterName',
        'publisher_id' => 'getPublisherId',
        'writer_group_name' => 'getWriterGroupName',
        'sequence_number' => 'getSequenceNumber',
        'meta_data_version' => 'getMetaDataVersion',
        'minor_version' => 'getMinorVersion',
        'timestamp' => 'getTimestamp',
        'status' => 'getStatus',
        'message_type' => 'getMessageType',
        'payload' => 'getPayload'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('data_set_writer_id', $data ?? [], 0);
        $this->setIfExists('data_set_writer_name', $data ?? [], null);
        $this->setIfExists('publisher_id', $data ?? [], null);
        $this->setIfExists('writer_group_name', $data ?? [], null);
        $this->setIfExists('sequence_number', $data ?? [], 0);
        $this->setIfExists('meta_data_version', $data ?? [], null);
        $this->setIfExists('minor_version', $data ?? [], 0);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('message_type', $data ?? [], null);
        $this->setIfExists('payload', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['data_set_writer_id']) && ($this->container['data_set_writer_id'] > 65535)) {
            $invalidProperties[] = "invalid value for 'data_set_writer_id', must be smaller than or equal to 65535.";
        }

        if (!is_null($this->container['data_set_writer_id']) && ($this->container['data_set_writer_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'data_set_writer_id', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['sequence_number']) && ($this->container['sequence_number'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'sequence_number', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['sequence_number']) && ($this->container['sequence_number'] < 0)) {
            $invalidProperties[] = "invalid value for 'sequence_number', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['minor_version']) && ($this->container['minor_version'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'minor_version', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['minor_version']) && ($this->container['minor_version'] < 0)) {
            $invalidProperties[] = "invalid value for 'minor_version', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets data_set_writer_id
     *
     * @return int|null
     */
    public function getDataSetWriterId()
    {
        return $this->container['data_set_writer_id'];
    }

    /**
     * Sets data_set_writer_id
     *
     * @param int|null $data_set_writer_id data_set_writer_id
     *
     * @return self
     */
    public function setDataSetWriterId($data_set_writer_id)
    {
        if (is_null($data_set_writer_id)) {
            throw new \InvalidArgumentException('non-nullable data_set_writer_id cannot be null');
        }

        if (($data_set_writer_id > 65535)) {
            throw new \InvalidArgumentException('invalid value for $data_set_writer_id when calling JsonDataSetMessage., must be smaller than or equal to 65535.');
        }
        if (($data_set_writer_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $data_set_writer_id when calling JsonDataSetMessage., must be bigger than or equal to 0.');
        }

        $this->container['data_set_writer_id'] = $data_set_writer_id;

        return $this;
    }

    /**
     * Gets data_set_writer_name
     *
     * @return string|null
     */
    public function getDataSetWriterName()
    {
        return $this->container['data_set_writer_name'];
    }

    /**
     * Sets data_set_writer_name
     *
     * @param string|null $data_set_writer_name data_set_writer_name
     *
     * @return self
     */
    public function setDataSetWriterName($data_set_writer_name)
    {
        if (is_null($data_set_writer_name)) {
            throw new \InvalidArgumentException('non-nullable data_set_writer_name cannot be null');
        }
        $this->container['data_set_writer_name'] = $data_set_writer_name;

        return $this;
    }

    /**
     * Gets publisher_id
     *
     * @return string|null
     */
    public function getPublisherId()
    {
        return $this->container['publisher_id'];
    }

    /**
     * Sets publisher_id
     *
     * @param string|null $publisher_id publisher_id
     *
     * @return self
     */
    public function setPublisherId($publisher_id)
    {
        if (is_null($publisher_id)) {
            throw new \InvalidArgumentException('non-nullable publisher_id cannot be null');
        }
        $this->container['publisher_id'] = $publisher_id;

        return $this;
    }

    /**
     * Gets writer_group_name
     *
     * @return string|null
     */
    public function getWriterGroupName()
    {
        return $this->container['writer_group_name'];
    }

    /**
     * Sets writer_group_name
     *
     * @param string|null $writer_group_name writer_group_name
     *
     * @return self
     */
    public function setWriterGroupName($writer_group_name)
    {
        if (is_null($writer_group_name)) {
            throw new \InvalidArgumentException('non-nullable writer_group_name cannot be null');
        }
        $this->container['writer_group_name'] = $writer_group_name;

        return $this;
    }

    /**
     * Gets sequence_number
     *
     * @return int|null
     */
    public function getSequenceNumber()
    {
        return $this->container['sequence_number'];
    }

    /**
     * Sets sequence_number
     *
     * @param int|null $sequence_number sequence_number
     *
     * @return self
     */
    public function setSequenceNumber($sequence_number)
    {
        if (is_null($sequence_number)) {
            throw new \InvalidArgumentException('non-nullable sequence_number cannot be null');
        }

        if (($sequence_number > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $sequence_number when calling JsonDataSetMessage., must be smaller than or equal to 4294967295.');
        }
        if (($sequence_number < 0)) {
            throw new \InvalidArgumentException('invalid value for $sequence_number when calling JsonDataSetMessage., must be bigger than or equal to 0.');
        }

        $this->container['sequence_number'] = $sequence_number;

        return $this;
    }

    /**
     * Gets meta_data_version
     *
     * @return \TechDock\OpcUaWebApiClient\Model\ConfigurationVersionDataType|null
     */
    public function getMetaDataVersion()
    {
        return $this->container['meta_data_version'];
    }

    /**
     * Sets meta_data_version
     *
     * @param \TechDock\OpcUaWebApiClient\Model\ConfigurationVersionDataType|null $meta_data_version meta_data_version
     *
     * @return self
     */
    public function setMetaDataVersion($meta_data_version)
    {
        if (is_null($meta_data_version)) {
            throw new \InvalidArgumentException('non-nullable meta_data_version cannot be null');
        }
        $this->container['meta_data_version'] = $meta_data_version;

        return $this;
    }

    /**
     * Gets minor_version
     *
     * @return int|null
     */
    public function getMinorVersion()
    {
        return $this->container['minor_version'];
    }

    /**
     * Sets minor_version
     *
     * @param int|null $minor_version minor_version
     *
     * @return self
     */
    public function setMinorVersion($minor_version)
    {
        if (is_null($minor_version)) {
            throw new \InvalidArgumentException('non-nullable minor_version cannot be null');
        }

        if (($minor_version > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $minor_version when calling JsonDataSetMessage., must be smaller than or equal to 4294967295.');
        }
        if (($minor_version < 0)) {
            throw new \InvalidArgumentException('invalid value for $minor_version when calling JsonDataSetMessage., must be bigger than or equal to 0.');
        }

        $this->container['minor_version'] = $minor_version;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \TechDock\OpcUaWebApiClient\Model\StatusCode|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \TechDock\OpcUaWebApiClient\Model\StatusCode|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets message_type
     *
     * @return string|null
     */
    public function getMessageType()
    {
        return $this->container['message_type'];
    }

    /**
     * Sets message_type
     *
     * @param string|null $message_type message_type
     *
     * @return self
     */
    public function setMessageType($message_type)
    {
        if (is_null($message_type)) {
            throw new \InvalidArgumentException('non-nullable message_type cannot be null');
        }
        $this->container['message_type'] = $message_type;

        return $this;
    }

    /**
     * Gets payload
     *
     * @return object|null
     */
    public function getPayload()
    {
        return $this->container['payload'];
    }

    /**
     * Sets payload
     *
     * @param object|null $payload payload
     *
     * @return self
     */
    public function setPayload($payload)
    {
        if (is_null($payload)) {
            throw new \InvalidArgumentException('non-nullable payload cannot be null');
        }
        $this->container['payload'] = $payload;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


