<?php
/**
 * SecurityGroupDataType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;

use \ArrayAccess;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * SecurityGroupDataType Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.12/#6.2.12.2).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SecurityGroupDataType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SecurityGroupDataType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'security_group_folder' => 'string[]',
        'key_lifetime' => 'float',
        'security_policy_uri' => 'string',
        'max_future_key_count' => 'int',
        'max_past_key_count' => 'int',
        'security_group_id' => 'string',
        'role_permissions' => '\TechDock\OpcUaWebApiClient\Model\RolePermissionType[]',
        'group_properties' => '\TechDock\OpcUaWebApiClient\Model\KeyValuePair[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'security_group_folder' => null,
        'key_lifetime' => 'double',
        'security_policy_uri' => null,
        'max_future_key_count' => 'int64',
        'max_past_key_count' => 'int64',
        'security_group_id' => null,
        'role_permissions' => null,
        'group_properties' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'security_group_folder' => false,
        'key_lifetime' => false,
        'security_policy_uri' => false,
        'max_future_key_count' => false,
        'max_past_key_count' => false,
        'security_group_id' => false,
        'role_permissions' => false,
        'group_properties' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'security_group_folder' => 'SecurityGroupFolder',
        'key_lifetime' => 'KeyLifetime',
        'security_policy_uri' => 'SecurityPolicyUri',
        'max_future_key_count' => 'MaxFutureKeyCount',
        'max_past_key_count' => 'MaxPastKeyCount',
        'security_group_id' => 'SecurityGroupId',
        'role_permissions' => 'RolePermissions',
        'group_properties' => 'GroupProperties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'security_group_folder' => 'setSecurityGroupFolder',
        'key_lifetime' => 'setKeyLifetime',
        'security_policy_uri' => 'setSecurityPolicyUri',
        'max_future_key_count' => 'setMaxFutureKeyCount',
        'max_past_key_count' => 'setMaxPastKeyCount',
        'security_group_id' => 'setSecurityGroupId',
        'role_permissions' => 'setRolePermissions',
        'group_properties' => 'setGroupProperties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'security_group_folder' => 'getSecurityGroupFolder',
        'key_lifetime' => 'getKeyLifetime',
        'security_policy_uri' => 'getSecurityPolicyUri',
        'max_future_key_count' => 'getMaxFutureKeyCount',
        'max_past_key_count' => 'getMaxPastKeyCount',
        'security_group_id' => 'getSecurityGroupId',
        'role_permissions' => 'getRolePermissions',
        'group_properties' => 'getGroupProperties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('security_group_folder', $data ?? [], null);
        $this->setIfExists('key_lifetime', $data ?? [], 0);
        $this->setIfExists('security_policy_uri', $data ?? [], null);
        $this->setIfExists('max_future_key_count', $data ?? [], 0);
        $this->setIfExists('max_past_key_count', $data ?? [], 0);
        $this->setIfExists('security_group_id', $data ?? [], null);
        $this->setIfExists('role_permissions', $data ?? [], null);
        $this->setIfExists('group_properties', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['max_future_key_count']) && ($this->container['max_future_key_count'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'max_future_key_count', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['max_future_key_count']) && ($this->container['max_future_key_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_future_key_count', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_past_key_count']) && ($this->container['max_past_key_count'] > 4294967295)) {
            $invalidProperties[] = "invalid value for 'max_past_key_count', must be smaller than or equal to 4294967295.";
        }

        if (!is_null($this->container['max_past_key_count']) && ($this->container['max_past_key_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_past_key_count', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets security_group_folder
     *
     * @return string[]|null
     */
    public function getSecurityGroupFolder()
    {
        return $this->container['security_group_folder'];
    }

    /**
     * Sets security_group_folder
     *
     * @param string[]|null $security_group_folder security_group_folder
     *
     * @return self
     */
    public function setSecurityGroupFolder($security_group_folder)
    {
        if (is_null($security_group_folder)) {
            throw new \InvalidArgumentException('non-nullable security_group_folder cannot be null');
        }
        $this->container['security_group_folder'] = $security_group_folder;

        return $this;
    }

    /**
     * Gets key_lifetime
     *
     * @return float|null
     */
    public function getKeyLifetime()
    {
        return $this->container['key_lifetime'];
    }

    /**
     * Sets key_lifetime
     *
     * @param float|null $key_lifetime key_lifetime
     *
     * @return self
     */
    public function setKeyLifetime($key_lifetime)
    {
        if (is_null($key_lifetime)) {
            throw new \InvalidArgumentException('non-nullable key_lifetime cannot be null');
        }
        $this->container['key_lifetime'] = $key_lifetime;

        return $this;
    }

    /**
     * Gets security_policy_uri
     *
     * @return string|null
     */
    public function getSecurityPolicyUri()
    {
        return $this->container['security_policy_uri'];
    }

    /**
     * Sets security_policy_uri
     *
     * @param string|null $security_policy_uri security_policy_uri
     *
     * @return self
     */
    public function setSecurityPolicyUri($security_policy_uri)
    {
        if (is_null($security_policy_uri)) {
            throw new \InvalidArgumentException('non-nullable security_policy_uri cannot be null');
        }
        $this->container['security_policy_uri'] = $security_policy_uri;

        return $this;
    }

    /**
     * Gets max_future_key_count
     *
     * @return int|null
     */
    public function getMaxFutureKeyCount()
    {
        return $this->container['max_future_key_count'];
    }

    /**
     * Sets max_future_key_count
     *
     * @param int|null $max_future_key_count max_future_key_count
     *
     * @return self
     */
    public function setMaxFutureKeyCount($max_future_key_count)
    {
        if (is_null($max_future_key_count)) {
            throw new \InvalidArgumentException('non-nullable max_future_key_count cannot be null');
        }

        if (($max_future_key_count > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $max_future_key_count when calling SecurityGroupDataType., must be smaller than or equal to 4294967295.');
        }
        if (($max_future_key_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_future_key_count when calling SecurityGroupDataType., must be bigger than or equal to 0.');
        }

        $this->container['max_future_key_count'] = $max_future_key_count;

        return $this;
    }

    /**
     * Gets max_past_key_count
     *
     * @return int|null
     */
    public function getMaxPastKeyCount()
    {
        return $this->container['max_past_key_count'];
    }

    /**
     * Sets max_past_key_count
     *
     * @param int|null $max_past_key_count max_past_key_count
     *
     * @return self
     */
    public function setMaxPastKeyCount($max_past_key_count)
    {
        if (is_null($max_past_key_count)) {
            throw new \InvalidArgumentException('non-nullable max_past_key_count cannot be null');
        }

        if (($max_past_key_count > 4294967295)) {
            throw new \InvalidArgumentException('invalid value for $max_past_key_count when calling SecurityGroupDataType., must be smaller than or equal to 4294967295.');
        }
        if (($max_past_key_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_past_key_count when calling SecurityGroupDataType., must be bigger than or equal to 0.');
        }

        $this->container['max_past_key_count'] = $max_past_key_count;

        return $this;
    }

    /**
     * Gets security_group_id
     *
     * @return string|null
     */
    public function getSecurityGroupId()
    {
        return $this->container['security_group_id'];
    }

    /**
     * Sets security_group_id
     *
     * @param string|null $security_group_id security_group_id
     *
     * @return self
     */
    public function setSecurityGroupId($security_group_id)
    {
        if (is_null($security_group_id)) {
            throw new \InvalidArgumentException('non-nullable security_group_id cannot be null');
        }
        $this->container['security_group_id'] = $security_group_id;

        return $this;
    }

    /**
     * Gets role_permissions
     *
     * @return \TechDock\OpcUaWebApiClient\Model\RolePermissionType[]|null
     */
    public function getRolePermissions()
    {
        return $this->container['role_permissions'];
    }

    /**
     * Sets role_permissions
     *
     * @param \TechDock\OpcUaWebApiClient\Model\RolePermissionType[]|null $role_permissions role_permissions
     *
     * @return self
     */
    public function setRolePermissions($role_permissions)
    {
        if (is_null($role_permissions)) {
            throw new \InvalidArgumentException('non-nullable role_permissions cannot be null');
        }
        $this->container['role_permissions'] = $role_permissions;

        return $this;
    }

    /**
     * Gets group_properties
     *
     * @return \TechDock\OpcUaWebApiClient\Model\KeyValuePair[]|null
     */
    public function getGroupProperties()
    {
        return $this->container['group_properties'];
    }

    /**
     * Sets group_properties
     *
     * @param \TechDock\OpcUaWebApiClient\Model\KeyValuePair[]|null $group_properties group_properties
     *
     * @return self
     */
    public function setGroupProperties($group_properties)
    {
        if (is_null($group_properties)) {
            throw new \InvalidArgumentException('non-nullable group_properties cannot be null');
        }
        $this->container['group_properties'] = $group_properties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


