<?php
/**
 * StructureType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPC UA Web API
 *
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: info@techdock.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TechDock\OpcUaWebApiClient\Model;
use \TechDock\OpcUaWebApiClient\ObjectSerializer;

/**
 * StructureType Class Doc Comment
 *
 * @category Class
 * @description [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part5/12.2.5/#12.2.5.3).
 * @package  TechDock\OpcUaWebApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StructureType
{
    /**
     * Possible values of this enum
     */
    public const STRUCTURE = 0;

    public const STRUCTURE_WITH_OPTIONAL_FIELDS = 1;

    public const UNION = 2;

    public const STRUCTURE_WITH_SUBTYPED_VALUES = 3;

    public const UNION_WITH_SUBTYPED_VALUES = 4;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STRUCTURE,
            self::STRUCTURE_WITH_OPTIONAL_FIELDS,
            self::UNION,
            self::STRUCTURE_WITH_SUBTYPED_VALUES,
            self::UNION_WITH_SUBTYPED_VALUES
        ];
    }
}


